// ui/src/lib/components/SeriesBrowser.svelte
<script lang="ts">
	import Card from '$lib/components/Card.svelte';
	import CardModal from '$lib/components/CardModal.svelte';
	import type { SeriesItem, SeriesDetail, SetCardItem, TcgCard } from '$shared/tcg';

	export let series: SeriesItem[] = [];

	// ── Column state (0=series, 1=sets, 2=cards) ─────────────────────────────
	let activeColumn = 0;

	let selectedSeries: SeriesItem | null = null;
	let selectedSet: { id: string; name: string } | null = null;

	let seriesDetail: SeriesDetail | null = null;
	let setCards: SetCardItem[] = [];

	let loadingColumn2 = false;
	let loadingColumn3 = false;
	let errorColumn2: string | null = null;
	let errorColumn3: string | null = null;

	let expandedCard: TcgCard | null = null;
	let failedSeriesLogos = new Set<string>();
	let failedSetLogos = new Set<string>();

	// Pagination
	const PAGE_SIZE = 40;
	let visibleCount = PAGE_SIZE;

	$: visibleCards = setCards.slice(0, visibleCount);
	$: hasMore = visibleCount < setCards.length;

	// ── Column 1 widths driven by activeColumn ────────────────────────────────
	$: col1Style = activeColumn === 0
		? 'width:100%;min-width:100%;'
		: activeColumn === 1
		? 'width:30%;min-width:30%;'
		: 'width:0;min-width:0;overflow:hidden;';

	$: col2Style = activeColumn === 0
		? 'width:0;min-width:0;overflow:hidden;'
		: activeColumn === 1
		? 'width:70%;min-width:70%;'
		: 'width:30%;min-width:30%;';

	$: col3Style = activeColumn < 2
		? 'width:0;min-width:0;overflow:hidden;'
		: 'width:70%;min-width:70%;';

	// ── Map SetCardItem → TcgCard for the Card component ─────────────────────
	function toTcgCard(item: SetCardItem): TcgCard {
		return {
			id: item.id,
			name: item.name,
			supertype: 'Pokemon',
			set: selectedSet?.name ?? '',
			number: item.localId,
			images: {
				small: item.image ? `${item.image}/low.webp` : '',
				large: item.image ? `${item.image}/high.webp` : ''
			}
		};
	}

	// ── Series tile click → fetch series detail ───────────────────────────────
	async function selectSeries(s: SeriesItem) {
		selectedSeries = s;
		selectedSet = null;
		seriesDetail = null;
		setCards = [];
		visibleCount = PAGE_SIZE;
		activeColumn = 1;
		loadingColumn2 = true;
		errorColumn2 = null;

		try {
			const res = await fetch(`/api/series/${encodeURIComponent(s.id)}`);
			const body = await res.json();
			if (!res.ok) throw new Error(body.error || `Failed to load series (${res.status})`);
			seriesDetail = body as SeriesDetail;
		} catch (e) {
			errorColumn2 = e instanceof Error ? e.message : 'Failed to load series';
		} finally {
			loadingColumn2 = false;
		}
	}

	// ── Set tile click → fetch set cards ─────────────────────────────────────
	async function selectSet(set: { id: string; name: string }) {
		selectedSet = set;
		setCards = [];
		visibleCount = PAGE_SIZE;
		activeColumn = 2;
		loadingColumn3 = true;
		errorColumn3 = null;

		try {
			const res = await fetch(`/api/sets/${encodeURIComponent(set.id)}/cards`);
			const body = await res.json();
			if (!res.ok) throw new Error(body.error || `Failed to load cards (${res.status})`);
			setCards = body as SetCardItem[];
		} catch (e) {
			errorColumn3 = e instanceof Error ? e.message : 'Failed to load cards';
		} finally {
			loadingColumn3 = false;
		}
	}

	// ── Breadcrumb navigation ─────────────────────────────────────────────────
	function goToSeries() {
		activeColumn = 0;
		selectedSeries = null;
		selectedSet = null;
		seriesDetail = null;
		setCards = [];
		errorColumn2 = null;
		errorColumn3 = null;
	}

	function goToSets() {
		activeColumn = 1;
		selectedSet = null;
		setCards = [];
		errorColumn3 = null;
	}

	// ── Retry handlers ────────────────────────────────────────────────────────
	function retryColumn2() {
		if (selectedSeries) selectSeries(selectedSeries);
	}

	function retryColumn3() {
		if (selectedSet) selectSet(selectedSet);
	}
</script>

<!-- Breadcrumb -->
{#if activeColumn > 0}
	<nav class="flex items-center gap-2 mb-4 text-sm font-geist text-ph-muted" aria-label="breadcrumb">
		<button
			type="button"
			class="hover:text-white transition-colors"
			on:click={goToSeries}
		>
			Series
		</button>
		{#if selectedSeries}
			<span class="text-ph-border">/</span>
			{#if activeColumn === 1}
				<span class="text-ph-text">{selectedSeries.name}</span>
			{:else}
				<button
					type="button"
					class="hover:text-white transition-colors"
					on:click={goToSets}
				>
					{selectedSeries.name}
				</button>
			{/if}
		{/if}
		{#if selectedSet && activeColumn === 2}
			<span class="text-ph-border">/</span>
			<span class="text-ph-text">{selectedSet.name}</span>
		{/if}
	</nav>
{/if}

<!-- Three-column layout -->
<div class="flex gap-4 overflow-hidden" style="min-height: 400px;">

	<!-- Column 1: Series grid -->
	<div
		class="transition-all duration-300 ease-in-out overflow-y-auto shrink-0"
		style={col1Style}
	>
		<div class="grid gap-3" style="grid-template-columns: repeat(auto-fill, minmax(min(140px, 100%), 1fr));">
			{#each series as s (s.id)}
				<button
					type="button"
					class="flex flex-col items-center gap-2 p-3 rounded-xl bg-ph-surface border border-ph-border hover:border-ph-accent hover:bg-ph-card transition-all duration-200 text-center"
					on:click={() => selectSeries(s)}
					aria-label={s.name}
				>
					{#if s.logo && !failedSeriesLogos.has(s.id)}
						<img
							src={s.logo}
							alt={s.name}
							class="w-full h-16 object-contain"
							loading="lazy"
							on:error={() => { failedSeriesLogos = new Set([...failedSeriesLogos, s.id]); }}
						/>
					{:else}
						<div class="w-full h-16 flex items-center justify-center bg-ph-card rounded-lg">
							<span class="text-xs text-ph-muted font-geist">{s.name[0]}</span>
						</div>
					{/if}
					<span class="text-xs font-geist font-medium text-ph-text leading-tight">{s.name}</span>
				</button>
			{/each}
		</div>
	</div>

	<!-- Column 2: Sets grid -->
	<div
		class="transition-all duration-300 ease-in-out overflow-y-auto shrink-0"
		style={col2Style}
	>
		{#if loadingColumn2}
			<div class="grid gap-3" style="grid-template-columns: repeat(auto-fill, minmax(min(120px, 100%), 1fr));">
				{#each Array.from({ length: 8 }) as _, i (i)}
					<div class="animate-pulse bg-ph-card rounded-xl h-32"></div>
				{/each}
			</div>
		{:else if errorColumn2}
			<div class="flex flex-col items-center gap-4 py-12 text-center">
				<p class="text-red-400 text-sm font-geist">{errorColumn2}</p>
				<button
					type="button"
					class="btn-primary w-auto px-4 py-2 text-sm"
					on:click={retryColumn2}
				>
					Retry
				</button>
			</div>
		{:else if seriesDetail}
			<div class="grid gap-3" style="grid-template-columns: repeat(auto-fill, minmax(min(120px, 100%), 1fr));">
				{#each seriesDetail.sets as set (set.id)}
					<button
						type="button"
						class="flex flex-col items-center gap-2 p-3 rounded-xl bg-ph-surface border border-ph-border hover:border-ph-accent hover:bg-ph-card transition-all duration-200 text-center"
						on:click={() => selectSet({ id: set.id, name: set.name })}
						aria-label={set.name}
					>
						{#if set.logo && !failedSetLogos.has(set.id)}
							<img
								src={set.logo}
								alt={set.name}
								class="w-full h-14 object-contain"
								loading="lazy"
								on:error={() => { failedSetLogos = new Set([...failedSetLogos, set.id]); }}
							/>
						{:else}
							<div class="w-full h-14 flex items-center justify-center bg-ph-card rounded-lg">
								<span class="text-xs text-ph-muted font-geist">{set.name[0]}</span>
							</div>
						{/if}
						<span class="text-xs font-geist font-medium text-ph-text leading-tight">{set.name}</span>
						<span class="text-xs text-ph-muted font-geist">{set.cardCount} cards</span>
					</button>
				{/each}
			</div>
		{/if}
	</div>

	<!-- Column 3: Card grid -->
	<div
		class="transition-all duration-300 ease-in-out overflow-y-auto shrink-0"
		style={col3Style}
	>
		{#if loadingColumn3}
			<div class="grid gap-3" style="grid-template-columns: repeat(auto-fill, minmax(min(140px, 100%), 1fr));">
				{#each Array.from({ length: PAGE_SIZE }) as _, i (i)}
					<div class="animate-pulse bg-ph-card rounded-xl aspect-[2.5/3.5]"></div>
				{/each}
			</div>
		{:else if errorColumn3}
			<div class="flex flex-col items-center gap-4 py-12 text-center">
				<p class="text-red-400 text-sm font-geist">{errorColumn3}</p>
				<button
					type="button"
					class="btn-primary w-auto px-4 py-2 text-sm"
					on:click={retryColumn3}
				>
					Retry
				</button>
			</div>
		{:else if setCards.length > 0}
			<div class="grid gap-3" style="grid-template-columns: repeat(auto-fill, minmax(min(140px, 100%), 1fr));">
				{#each visibleCards as item (item.id)}
					<Card card={toTcgCard(item)} on:expand={(e) => (expandedCard = e.detail)} />
				{/each}
			</div>

			{#if hasMore}
				<div class="mt-8 flex justify-center">
					<button
						type="button"
						class="btn-primary w-auto px-8"
						on:click={() => (visibleCount += PAGE_SIZE)}
					>
						Load more
					</button>
				</div>
			{/if}
		{/if}
	</div>
</div>

{#if expandedCard}
	<CardModal card={expandedCard} on:close={() => (expandedCard = null)} />
{/if}

// ui/src/lib/components/SeriesBrowser.tsx
'use client';

import { useState, useCallback } from 'react';
import type { SeriesItem, SeriesDetail, SetCardItem, TcgCard } from '$shared/tcg';
import { Card } from './Card';
import { CardModal } from './CardModal';
import styles from './SeriesBrowser.module.css';

export interface SeriesBrowserProps {
  series?: SeriesItem[];
  onSelect?: (card: TcgCard) => void;
}

const PAGE_SIZE = 40;

function toTcgCard(item: SetCardItem, setName: string): TcgCard {
  return {
    id: item.id,
    name: item.name,
    supertype: 'Pokemon',
    set: setName,
    number: item.localId,
    images: {
      small: item.image ? `${item.image}/low.webp`  : '',
      large: item.image ? `${item.image}/high.webp` : '',
    },
  };
}

export function SeriesBrowser({ series = [], onSelect }: SeriesBrowserProps) {
  const [activeColumn, setActiveColumn]       = useState(0);
  const [selectedSeries, setSelectedSeries]   = useState<SeriesItem | null>(null);
  const [selectedSet, setSelectedSet]         = useState<{ id: string; name: string } | null>(null);
  const [seriesDetail, setSeriesDetail]       = useState<SeriesDetail | null>(null);
  const [setCards, setSetCards]               = useState<SetCardItem[]>([]);
  const [loadingCol2, setLoadingCol2]         = useState(false);
  const [loadingCol3, setLoadingCol3]         = useState(false);
  const [errorCol2, setErrorCol2]             = useState<string | null>(null);
  const [errorCol3, setErrorCol3]             = useState<string | null>(null);
  const [expandedCard, setExpandedCard]       = useState<TcgCard | null>(null);
  const [visibleCount, setVisibleCount]       = useState(PAGE_SIZE);
  const [failedSeriesLogos, setFailedSeriesLogos] = useState<Set<string>>(new Set());
  const [failedSetLogos, setFailedSetLogos]       = useState<Set<string>>(new Set());

  const visibleCards = setCards.slice(0, visibleCount);
  const hasMore = visibleCount < setCards.length;

  const col1Style: React.CSSProperties = activeColumn === 0
    ? { width: '100%', minWidth: '100%' }
    : activeColumn === 1
    ? { width: '30%', minWidth: '30%' }
    : { width: 0, minWidth: 0, overflow: 'hidden' };

  const col2Style: React.CSSProperties = activeColumn === 0
    ? { width: 0, minWidth: 0, overflow: 'hidden' }
    : activeColumn === 1
    ? { width: '70%', minWidth: '70%' }
    : { width: '30%', minWidth: '30%' };

  const col3Style: React.CSSProperties = activeColumn < 2
    ? { flex: 'none', width: 0, minWidth: 0, overflow: 'hidden' }
    : { flex: 1, minWidth: 0 };

  const selectSeries = useCallback(async (s: SeriesItem) => {
    setSelectedSeries(s);
    setSelectedSet(null);
    setSeriesDetail(null);
    setSetCards([]);
    setVisibleCount(PAGE_SIZE);
    setActiveColumn(1);
    setLoadingCol2(true);
    setErrorCol2(null);
    try {
      const res  = await fetch(`/api/series/${encodeURIComponent(s.id)}`);
      const body = await res.json() as SeriesDetail & { error?: string };
      if (!res.ok) throw new Error(body.error ?? `Failed to load series (${res.status})`);
      setSeriesDetail(body);
    } catch (e) {
      setErrorCol2(e instanceof Error ? e.message : 'Failed to load series');
    } finally {
      setLoadingCol2(false);
    }
  }, []);

  const selectSet = useCallback(async (set: { id: string; name: string }) => {
    setSelectedSet(set);
    setSetCards([]);
    setVisibleCount(PAGE_SIZE);
    setActiveColumn(2);
    setLoadingCol3(true);
    setErrorCol3(null);
    try {
      const res  = await fetch(`/api/sets/${encodeURIComponent(set.id)}/cards`);
      const body = await res.json() as { cards?: SetCardItem[]; error?: string };
      if (!res.ok) throw new Error(body.error ?? `Failed to load set (${res.status})`);
      setSetCards(body.cards ?? []);
    } catch (e) {
      setErrorCol3(e instanceof Error ? e.message : 'Failed to load set');
    } finally {
      setLoadingCol3(false);
    }
  }, []);

  return (
    <>
      <div className={styles['series-browser']}>
        {/* Column 1: Series list */}
        <div className={styles['series-browser__col']} style={col1Style}>
          <div className={styles['series-browser__col-inner']}>
            <div className={styles['series-grid']}>
              {series.map((s) => (
                <button
                  key={s.id}
                  className={`${styles['series-tile']} ${selectedSeries?.id === s.id ? styles['series-tile--active'] : ''}`}
                  onClick={() => selectSeries(s)}
                >
                  {s.logo && !failedSeriesLogos.has(s.id) ? (
                    <img
                      src={s.logo}
                      alt={s.name}
                      className={styles['series-tile__logo']}
                      onError={() => setFailedSeriesLogos(prev => new Set(prev).add(s.id))}
                    />
                  ) : (
                    <span className={styles['series-tile__name']}>{s.name}</span>
                  )}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Column 2: Sets list */}
        <div className={styles['series-browser__col']} style={col2Style}>
          <div className={styles['series-browser__col-inner']}>
            {loadingCol2 && <p className={styles['series-browser__status']}>Loading…</p>}
            {errorCol2   && <p className={styles['series-browser__error']}>{errorCol2}</p>}
            {seriesDetail?.sets && (
              <div className={styles['set-grid']}>
                {seriesDetail.sets.map((set) => (
                  <button
                    key={set.id}
                    className={`${styles['set-tile']} ${selectedSet?.id === set.id ? styles['set-tile--active'] : ''}`}
                    onClick={() => selectSet({ id: set.id, name: set.name })}
                  >
                    {set.logo && !failedSetLogos.has(set.id) ? (
                      <img
                        src={set.logo}
                        alt={set.name}
                        className={styles['set-tile__logo']}
                        onError={() => setFailedSetLogos(prev => new Set(prev).add(set.id))}
                      />
                    ) : (
                      <div className={styles['set-tile__fallback']}>{set.name[0]}</div>
                    )}
                    <span className={styles['set-tile__name']}>{set.name}</span>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Column 3: Cards grid */}
        <div className={styles['series-browser__col']} style={col3Style}>
          <div className={styles['series-browser__col-inner']}>
            {loadingCol3 && <p className={styles['series-browser__status']}>Loading…</p>}
            {errorCol3   && <p className={styles['series-browser__error']}>{errorCol3}</p>}
            <ul className={styles['card-grid']} role="list">
              {visibleCards.map((item) => {
                const tcgCard = toTcgCard(item, selectedSet?.name ?? '');
                return (
                  <Card
                    key={item.id}
                    card={tcgCard}
                    onExpand={(c) => { setExpandedCard(c); onSelect?.(c); }}
                  />
                );
              })}
            </ul>
            {hasMore && (
              <button
                className={styles['series-browser__load-more']}
                onClick={() => setVisibleCount(n => n + PAGE_SIZE)}
              >
                Load more
              </button>
            )}
          </div>
        </div>
      </div>

      {expandedCard && (
        <CardModal card={expandedCard} onClose={() => setExpandedCard(null)} />
      )}
    </>
  );
}
